[package]
name = "thrive"
version = "0.0.1"
edition = "2021"

[dependencies]
avian3d = "0.3.1"
bevy = "0.16.1"
noisy_bevy = "0.10.1"
bytemuck = "1.23.2"
noiz = { git = "https://github.com/ElliottjPierce/noiz" }
smallvec = "1.15.1"
serde = { version = "1.0.219", features = ["derive"] }